#!/usr/bin/env python3
"""Census: files that look generated or vendored, so a reviewer skips them.

Output: TSV `reason<TAB>path`, sorted by path asc. Walks everything except
.git — finding vendored dirs is the job, so they are not pruned.
Exit codes: 0 = ok (or --fail-if-found unset), 1 = hits found and
--fail-if-found set, 2 = usage/environment error.
"""
import argparse
import os
import sys

VENDORED_DIRS = {"node_modules", "vendor", "vendors", "third_party", "thirdparty", "bower_components"}
BUILD_DIRS = {"dist", "build", "out", "target"}
GENERATED_MARKERS = ("do not edit", "@generated", "code generated by", "autogenerated", "auto-generated")
PROTO_SUFFIXES = ("_pb2.py", "_pb2_grpc.py", ".pb.go", ".pb.cc")


def is_binary(path):
    try:
        with open(path, "rb") as f:
            return b"\x00" in f.read(8192)
    except OSError:
        return True


def norm(path):
    return os.path.relpath(path).replace(os.sep, "/")


def detect(path):
    parts = set(norm(path).split("/")[:-1])
    name = os.path.basename(path).lower()
    if parts & VENDORED_DIRS:
        return "vendored-dir"
    if parts & BUILD_DIRS:
        return "build-output-dir"
    if name.endswith((".min.js", ".min.css")):
        return "minified"
    if name.endswith(".map"):
        return "sourcemap"
    if name.endswith(PROTO_SUFFIXES):
        return "generated-proto"
    if not is_binary(path):
        try:
            with open(path, "r", encoding="utf-8", errors="replace") as f:
                for _ in range(5):
                    line = f.readline().lower()
                    if not line:
                        break
                    if any(marker in line for marker in GENERATED_MARKERS):
                        return "generated-marker"
        except OSError:
            pass
    return None


def main():
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("paths", nargs="*", default=["."], help="files or directories (default: .)")
    parser.add_argument("--fail-if-found", action="store_true",
                        help="exit 1 when any generated/vendored file is found (default: report-only)")
    args = parser.parse_args()

    try:
        sys.stdout.reconfigure(encoding="utf-8", newline="\n")
    except AttributeError:
        pass

    for p in args.paths or ["."]:
        if not os.path.exists(p):
            print(f"error: no such path: {p}", file=sys.stderr)
            return 2

    rows = []
    for root in args.paths or ["."]:
        if os.path.isfile(root):
            reason = detect(root)
            if reason:
                rows.append((reason, norm(root)))
            continue
        for dirpath, dirnames, filenames in os.walk(root):
            dirnames[:] = sorted(d for d in dirnames if d != ".git")
            for name in sorted(filenames):
                path = os.path.join(dirpath, name)
                reason = detect(path)
                if reason:
                    rows.append((reason, norm(path)))

    rows.sort(key=lambda r: r[1])

    print("reason\tpath")
    for reason, path in rows:
        print(f"{reason}\t{path}")

    return 1 if rows and args.fail_if_found else 0


if __name__ == "__main__":
    sys.exit(main())
